### ISSUE TITLE
Table Cell padding should be 16px on horizontal direction

### ISSUE THREAD

**Issue by huayunh** [brightlayer-ui/angular-themes#38]
#### Describe the desired behavior

The rule should go like this:

```css
th.mat-header-cell, td.mat-cell, td.mat-footer-cell {
    padding-left: 16px;
    padding-right: 16px;
}
```

per [material design's design spec](https://material.io/components/data-tables#specs):

![image](https://user-images.githubusercontent.com/8997218/137419555-d79ef4e7-12a6-424f-a67e-77ccea07aea3.png)

#### Describe the current behavior

It has a 24px heading on `:first-of-type` and `:last-of-type`, which only adds padding to `<td>`'s in the first and last column
